site_name: 考研复习

repo_name: 'gzttcydxx/Postgraduate-entrance-examination-review'
repo_url: 'https://github.com/gzttcydxx/Postgraduate-entrance-examination-review'

theme:
  name: material
  language: 'zh'
  features:
    - navigation.tabs
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - abbr
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - codehilite:
      guess_lang: true
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
      # emoji_generator: !!python/name:pymdownx.emoji.to_svg
      # emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      # emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      # emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      # emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.keys
  # - pymdownx.progressbar

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gzttcydxx
      name: gzttcydxx
    - icon: fontawesome/brands/behance
      link: https://github.com/gzttcydxx
    - icon: fontawesome/brands/docker
      link: https://github.com/gzttcydxx
    - icon: fontawesome/brands/instagram
      link: https://github.com/gzttcydxx
    - icon: fontawesome/brands/linkedin
      link: https://github.com/gzttcydxx
    - icon: fontawesome/brands/medium
      link: https://github.com/gzttcydxx
    - icon: fontawesome/brands/pied-piper-alt
      link: https://github.com/gzttcydxx
    - icon: fontawesome/brands/product-hunt
      link: https://github.com/gzttcydxx
    - icon: fontawesome/brands/slack
      link: https://github.com/gzttcydxx
    - icon: fontawesome/brands/twitter
      link: https://github.com/gzttcydxx
  search:
    -language: jp

extra_javascript:
  # - 'js/extra.js'
  # - 'js/baidu-tongji.js'
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  # - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tablesort.min.js
  # - js/MathJax.js
  - javascripts/tablesort.js
  - js/pdfobject.min.js
  - js/jquery-1.7.1.min.js
  - js/jquery.media.js

nav:
  # - 一. 介绍: index.md
  # - 二. 幻灯片: beamer.md
  - 数学: 数学/第13届数学竞赛.md
  # - 专业课: 专业课
  - 政治:
    - 史纲: 政治/史纲.md
    - 毛中特: 政治/毛中特.md
  - 英语:
    - 单词:
      - Day 1 商业经济类1: 英语/单词/day1.md
      - Day 2 商业经济类2: 英语/单词/day2.md
      - Day 3 法律政治类1: 英语/单词/day3.md
      - Day 4 法律政治类2: 英语/单词/day4.md
      - Day 5 社会民生类1: 英语/单词/day5.md
      - Day 6 社会民生类2: 英语/单词/day6.md
      - Day 7 教育学术类1: 英语/单词/day7.md
      - Day 8 教育学术类2: 英语/单词/day8.md
      - Day 9 医疗健康类1: 英语/单词/day9.md
      - Day 10 医疗健康类2: 英语/单词/day10.md
      - Day 11 科技信息类: 英语/单词/day11.md
      - Day 12 环境保护类: 英语/单词/day12.md
      - Day 13 数据描述类: 英语/单词/day13.md
      - Day 14 易混词辨析（名词篇）1: 英语/单词/day14.md
      - Day 15 易混词辨析（名词篇）2: 英语/单词/day15.md
      - Day 16 易混词辨析（动词篇）1: 英语/单词/day16.md
      - Day 17 易混词辨析（动词篇）2: 英语/单词/day17.md
      - Day 18 易混词辨析（形容词篇）1: 英语/单词/day18.md
      - Day 19 易混词辨析（形容词篇）2: 英语/单词/day19.md
      - Day 20 新大纲词补充1: 英语/单词/day20.md
      - Day 21 新大纲词补充2: 英语/单词/day21.md
    - 作文:
      - 应用文写作: 英语/作文.md

copyright: Copyright &copy; 2021 - 2022 gzttcydxx